# Generated by Django 4.1.6 on 2023-02-15 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0003_alter_subtopic_options_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
